server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sca-provider
  consumer:
    check: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zetd9474ydd1g5955o.mysql.rds.aliyuncs.com:3306/yuhb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: workshop
    password: Workshop123

  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848
#    alibaba:
#      seata:
#      # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.sca-customer-seata-tx-service-group
#        tx-service-group: sca-customer-seata-tx-service-group

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: sca-customer
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  service:
    vgroup-mapping:
      my_test_tx_group: default
  grouplist:
    default: 127.0.0.1:8091
  enable-degrade: false
  disable-global-transaction: false


